export const AR = {
  app: {
    name: "POULTRIX",
    title: "منصة ذكاء الدواجن",
    subtitle: "من الفوضى إلى السيطرة",
  },
  nav: {
    dashboard: "لوحة القيادة",
    chickens: "الدجاج",
    eggs: "البيض",
    meat: "اللحم",
    breeds: "سلالات الدجاج",
    articles: "المقالات",
    feed: "العلف",
    aiVet: "AI البيطري",
    analytics: "التحليلات",
    finance: "المالية",
    alerts: "التنبيهات",
    reports: "التقارير",
    settings: "الإعدادات",
    overview: "نظرة عامة",
  },
  dashboard: {
    title: "لوحة القيادة",
    subtitle: "نظرة شاملة على ضيعتك في الوقت الحقيقي",
    live: "مباشر",
    offline: "غير متصل",
    loading: "جاري التحميل...",
    noData: "لا توجد بيانات متاحة",
  },
  metrics: {
    mortality: "معدل النفوق",
    feed: "كفاءة العلف",
    health: "صحة القطيع",
    profit: "هامش الربح",
    totalBirds: "إجمالي الطيور",
    activeBarns: "الحظائر النشطة",
    avgAge: "متوسط العمر",
    healthScore: "مؤشر الصحة",
    dailyEggs: "البيض اليومي",
    avgWeight: "الوزن المتوسط",
    waterUsage: "استهلاك الماء",
  },
  financial: {
    dailyFeed: "العلف اليومي",
    dailyWater: "الماء اليومي",
    projectedRevenue: "الإيراد المتوقع",
    profitMargin: "هامش الربح",
    costPerBird: "التكلفة لكل طير",
    breakEven: "نقطة التعادل",
    roi: "العائد على الاستثمار",
    feedCostPercent: "نسبة تكلفة العلف",
    laborCost: "تكلفة اليد العاملة",
    medicationCost: "تكلفة الدواء",
    utilitiesCost: "تكلفة المرافق",
    budgetVsActual: "الميزانية مقابل الفعلي",
    revenue: "الإيرادات",
    costs: "التكاليف",
    profit: "الربح",
  },
  alerts: {
    allClear: "كلشي مستقر — لا توجد تنبيهات نشيطة",
    noAlerts: "لا توجد تنبيهات",
    high: "عالية",
    medium: "متوسطة",
    low: "منخفضة",
    acknowledge: "تأكيد",
    barn: "الحظيرة",
  },
  breeds: {
    title: "سلالات الدجاج",
    subtitle: "سلالة مختلفة",
    search: "بحث عن سلالة...",
    notFound: "لم يتم العثور على السلالة",
    back: "العودة إلى السلالات",
    origin: "المنشأ",
    eggColor: "لون البيض",
    eggSize: "حجم البيض",
    eggsPerYear: "البيض سنوياً",
    temperament: "الطباع",
    description: "وصف السلالة",
    sources: "المصادر",
  },
  actions: {
    add: "إضافة",
    search: "بحث",
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    confirm: "تأكيد",
    generate: "توليد",
    download: "تحميل",
    viewAll: "عرض الكل",
    signIn: "تسجيل الدخول",
    signUp: "ابدأ الآن",
    getStarted: "ابدأ مجاناً",
    tryFree: "جرب 30 يوم مجاناً",
    learnMore: "اكتشف",
  },
  status: {
    excellent: "ممتاز",
    good: "جيد",
    average: "متوسط",
    low: "منخفض",
    ready: "جاهز",
    growing: "ينمو",
    small: "صغير",
  },
  errors: {
    network: "خطأ في الشبكة. تحقق من اتصالك بالإنترنت.",
    unauthorized: "انتهت الجلسة. الرجاء تسجيل الدخول مرة أخرى.",
    notFound: "الملف المطلوب غير موجود.",
    rateLimit: "طلبات كثيرة. الرجاء التهدئة قليلاً.",
    server: "خطأ داخلي في الخادم. تم إبلاغ الفريق التقني.",
    validation: "بيانات غير صالحة. الرجاء التحقق من المدخلات.",
  },
  feed: {
    title: "إدارة العلف",
    subtitle: "مراقبة مخزون العلف واستهلاكه",
    stock: "المخزون",
    dailyConsumption: "الاستهلاك اليومي",
    lowStockAlerts: "تنبيهات انخفاض المخزون",
    feedType: "نوع العلف",
    currentKg: "الكمية الحالية",
    minThreshold: "الحد الأدنى",
    costPerKg: "التكلفة لكل كغ",
    supplier: "المورد",
    noData: "لا توجد بيانات علف بعد. أضف أول دفعة علف.",
  },
  analytics: {
    title: "التحليلات",
    subtitle: "تحليلات شاملة لأداء الضيعة",
    period: "الفترة",
    days7: "7 أيام",
    days30: "30 يوم",
    days90: "90 يوم",
    mortalityTrend: "اتجاه النفوق",
    eggProduction: "إنتاج البيض",
    financialTrend: "الاتجاه المالي",
    healthTrend: "اتجاه الصحة",
    noData: "ابدأ التتبع لترى تحليلاتك",
  },
  finance: {
    title: "المركز المالي",
    subtitle: "نظرة شاملة على الوضع المالي لضيعتك",
    expenseBreakdown: "تفاصيل المصروفات",
    revenueVsCost: "الإيرادات مقابل التكاليف",
    projections: "التوقعات المالية",
    breakevenCalc: "حاسبة نقطة التعادل",
    currentPrice: "السعر الحالي لكل كغ",
    breakevenPrice: "سعر التعادل",
    budgetActual: "الميزانية مقابل الفعلي",
    month: "الشهر",
    budgeted: "الميزانية",
    actual: "الفعلي",
    variance: "الفرق",
    noData: "تتبع مصروفاتك الأولى لترى الرؤى المالية",
  },
  notifications: {
    title: "التنبيهات",
    subtitle: "سجل التنبيهات والإشعارات",
    filterAll: "الكل",
    filterHigh: "عالية",
    filterMedium: "متوسطة",
    filterLow: "منخفضة",
    acknowledged: "تم التأكيد",
    noAlerts: "كل شيء هادئ! لا توجد تنبيهات نشيطة.",
    newAlert: "تنبيه جديد",
  },
  reports: {
    title: "التقارير",
    subtitle: "توليد وتحميل تقارير الضيعة",
    production: "الإنتاج",
    financial: "المالي",
    health: "الصحي",
    flock: "القطيع",
    thisWeek: "هذا الأسبوع",
    thisMonth: "هذا الشهر",
    thisQuarter: "هذا الربع",
    format: "الصيغة",
    formatHtml: "HTML",
    formatPdf: "PDF",
    formatExcel: "Excel",
    generate: "توليد التقرير",
    recentReports: "آخر التقارير",
    noData: "توليد أول تقرير لك",
  },
  settings: {
    title: "الإعدادات",
    subtitle: "إعدادات الضيعة والحساب",
    farmProfile: "معلومات الضيعة",
    farmName: "اسم الضيعة",
    location: "الموقع",
    barnCount: "عدد الحظائر",
    primaryBreed: "السلالة الرئيسية",
    notifications: "إعدادات الإشعارات",
    emailNotifs: "الإشعارات البريدية",
    pushNotifs: "إشعارات التطبيق",
    smsNotifs: "إشعارات SMS",
    apiKeys: "مفاتيح API",
    users: "المستخدمون",
    dangerZone: "منطقة الخطر",
    deleteData: "حذف بيانات الضيعة",
    deleteWarning: "هذا الإجراء لا يمكن التراجع عنه. سيتم حذف جميع بيانات ضيعتك.",
  },
  ai: {
    title: "ذكاء POULTRIX",
    subtitle: "تحليلات وتوقعات لحظية",
    confidence: "نسبة الثقة",
    noData: "لا توجد بيانات متاحة",
    processing: "جاري التحليل...",
    predictions: "التوقعات",
    recommendations: "التوصيات",
  },
};
